version: '3.8'

services:
  # PHP-FPM service for Symfony
  php:
    image: php:8.1-fpm
    container_name: symfony_web
    volumes:
      - ./..:/var/www/html
    working_dir: /var/www/html
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://root:password@db/mysql_db
      - REDIS_URL=redis://redis
    networks:
      - symfony_network

  # Nginx service for web server
  web:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./..:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - symfony_network

  # MySQL service
  db:
    image: mysql:latest
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=main
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony_network

  # Redis service
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - symfony_network

volumes:
  mysql_data:
    driver: local

networks:
  symfony_network:
    driver: bridge
